apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
      name: {{ .Chart.Name }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: Always
          env:
            {{- $envmap := .Values.envmap | default "" | fromYaml | default dict -}}
            {{- $envmapdata := $envmap.data | default dict -}}
            {{- $env := .Values.env | default dict -}}
            {{- range $key, $value := merge $envmapdata $env }}
            - name: {{ $key | upper }}
              value: {{ $value | quote }}
            {{- end }}
      imagePullSecrets:
        - name: {{ .Chart.Name }}-registry
