apiVersion: v1
kind: Service
metadata:
  labels:
    app: {{ .Chart.Name }}
  name: {{ .Chart.Name }}
spec:
  type: ClusterIP
  ports:
    - name: {{ .Chart.Name }}-api-forward
      port: 8080
      protocol: TCP
      targetPort: {{ .Values.service.internalPort }}
  selector:
    app: {{ .Chart.Name }}
  sessionAffinity: None
